[package]
name = "scion"
version = "0.2.0"
authors = ["grzi <jeremy.thulliez@gmail.com>"]
edition = "2018"
description = "Game making library on top of wgpu, winit, legion"
documentation = "https://docs.rs/scion"
keywords = ["game", "library", "engine"]
repository = "https://github.com/grzi/scion/"
license = "MIT OR Apache-2.0"

[features]
parallel = ["legion/parallel"]

[dependencies]
legion = { version = "0.4", default-features = false, features = ["codegen"] }

# window & rendering
winit = "0.24.0"
wgpu = "0.7.0"
futures = "0.3"

# maths
ultraviolet = "0.8"

# serialization
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
bytemuck = { version = "1.4", features = ["derive"] }
image = { version = "0.23", default-features = false, features = ["png"] }

# logging
log = { version = "0.4.14", features = ["serde"] }
fern = { version = "0.6.0", features = ["colored"] }

[profile.dev.package]
image = { opt-level = 3 }
png = { opt-level = 3 }
bitflags = { opt-level = 3 }
bytemuck = { opt-level = 3 }
byteorder = { opt-level = 3 }
miniz_oxide = { opt-level = 3 }
adler32 = { opt-level = 3 }
deflate = { opt-level = 3 }

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.1"
glob = "0.3"
shaderc = "0.7"

[dev-dependencies]
rand = "0.8.3"